In [2]:
import numpy as np
a= np.arange(12)
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
#flat

a= np.arange(12).reshape(3,4)
print(a)
for x in a.flat:
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
a= np.arange(12).reshape(3,4)
print(a)

b=a.flatten()#默认是按order='C'
print(b)

c=a.flatten(order='F')
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]
