In [9]:
import numpy as np
arr=np.arange(12).reshape(4,3)
print(arr)
print('\n')
for x in np.nditer(arr.T):
    print(x,end=',')
print('\n')

print('-'*20)


b=arr.T.copy(order='C')
print(b)
print('\n')
for x in np.nditer(b):
    print(x,end=',')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


0,1,2,3,4,5,6,7,8,9,10,11,

--------------------
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


0,3,6,9,1,4,7,10,2,5,8,11,