In [ ]:
#numpy学习

做科学计算的基础库,重在数值计算,也是大部分python的科学计算库的基础库,多用在大型,多维数组上执行数值运算

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array(range(1,6))
c=np.arange(1,6)
print(a)
print(b)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


上面的a,b,c内容相同,arange和range不同
np.arange()的用法:arange([start,]stop[,step,],dtype=None)