In [9]:
import numpy as np
t1=np.arange(12)
print(t1)
print(t1.shape)


t2=np.array([[1,2,3,4],[5,6,7,8]])
print(t2)
print(t2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
