In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[[0,1,2],[0,1,0]])

[1 5 7]


前面的是行坐标,后面的是列坐标

In [2]:
arr=np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[ 10, 11, 12]])
print('我们的数组是:')
print(arr)
print('\n')
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
arr2=arr[rows,cols]
print('这四个角的元素是:')
print(arr2)

我们的数组是:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


这四个角的元素是:
[[ 1  3]
 [10 12]]


In [3]:
arr=np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[ 10, 11, 12]])
print(arr[arr>5])

[ 6  7  8  9 10 11 12]
