In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
#元素类型要相同
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
#多维数组
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr=np.array([1,2,3,4,5,6,7,8],ndmin=2)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [11]:
#dtype参数
arr=np.array([1,2,3,4],dtype=np.float32)
arr

array([1., 2., 3., 4.], dtype=float32)

In [12]:
#dtype参数
arr=np.array([1,2,3,4],dtype="f")
arr

array([1., 2., 3., 4.], dtype=float32)

In [16]:
#结构化数据
student=np.dtype([('name','S20'),('age','i4'),('score','f4')])
arr= np.array([('pjl',18,99)],dtype=student)
arr

array([(b'pjl', 18, 99.)],
      dtype=[('name', 'S20'), ('age', '<i4'), ('score', '<f4')])

In [18]:
#asarray函数
import numpy as np
s=[1,2,3,4,5]
arr=np.asarray(s)
arr

array([1, 2, 3, 4, 5])

In [20]:
arr=np.asarray((1,2,3,4,5))#元组
arr

array([1, 2, 3, 4, 5])

In [22]:
arr=np.asarray([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr=np.asarray([1, 2, 3, 4, 5],dtype='f')
arr

array([1., 2., 3., 4., 5.], dtype=float32)