In [6]:
import numpy as np
arr=np.arange(24)
# arr
arr.reshape(4,6)
arr2=arr.reshape(2,4,3)
arr2


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [10]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.size)
print(arr.dtype)


[[1 2 3]
 [4 5 6]]
6
int64
