In [1]:
import numpy as np
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [3]:
arr=np.ones([3,2],dtype=int)
arr

array([[1, 1],
       [1, 1],
       [1, 1]])

In [4]:
#full()函数
arr=np.full(5,fill_value=1024)
arr

array([1024, 1024, 1024, 1024, 1024])

In [6]:
arr=np.full([3,2],fill_value=1024,dtype=int)
arr

array([[1024, 1024],
       [1024, 1024],
       [1024, 1024]])

In [ ]:
#eye()函数
#对角线为1 的一个