In [1]:
import numpy as np
arr=np.random.rand()
arr

0.19089432370729376

In [2]:
arr=np.random.rand(3,2)
arr

array([[0.19454407, 0.36195304],
       [0.16521567, 0.73329638],
       [0.94752104, 0.63313415]])

In [3]:
arr=np.random.random(2)
arr

array([0.30703843, 0.3483256 ])

In [7]:
arr=np.random.randint(1,10,100)
arr

array([7, 9, 7, 8, 6, 3, 1, 5, 5, 4, 5, 1, 1, 6, 7, 4, 5, 8, 6, 9, 7, 6,
       8, 8, 4, 6, 2, 6, 4, 3, 5, 9, 5, 1, 2, 3, 7, 6, 5, 8, 4, 4, 4, 7,
       6, 4, 4, 7, 5, 4, 1, 2, 2, 3, 8, 6, 9, 2, 6, 3, 3, 1, 5, 4, 5, 4,
       8, 9, 7, 5, 1, 1, 7, 6, 7, 4, 3, 6, 2, 8, 1, 3, 2, 4, 7, 2, 8, 6,
       4, 7, 4, 2, 5, 1, 7, 2, 2, 5, 6, 6], dtype=int32)

In [10]:
arr=np.random.randn(3)
arr

array([-1.08359975, -0.87351127,  1.79898758])

In [12]:
arr=np.random.normal()
arr

-0.7553593481390263