In [20]:
import numpy as np


t1=np.arange(0,24).reshape(4,6)
# print(t1)

print(t1[:,2:4])
print(' ')

t1[:,2:4]=0
print(t1)

print(t1<10)

t2=np.where(t1<10,1,0)
print(t2)

t1=t1.astype(float)
t1[2:,2:]=np.nan
print(t1)


t4=np.clip(t1,5,10)
print(t4)

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]
 
[[ 0  1  0  0  4  5]
 [ 6  7  0  0 10 11]
 [12 13  0  0 16 17]
 [18 19  0  0 22 23]]
[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False  True  True False False]
 [False False  True  True False False]]
[[1 1 1 1 1 1]
 [1 1 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]]
[[ 0.  1.  0.  0.  4.  5.]
 [ 6.  7.  0.  0. 10. 11.]
 [12. 13. nan nan nan nan]
 [18. 19. nan nan nan nan]]
[[ 5.  5.  5.  5.  5.  5.]
 [ 6.  7.  5.  5. 10. 10.]
 [10. 10. nan nan nan nan]
 [10. 10. nan nan nan nan]]
