In [6]:
import numpy as np
t1=np.array([[0,1,2,3,4,5]
            ,[6,7,8,9,10,11]
             ])
t2=np.arange(12,24).reshape(2,6)
print(t1)
print(t2)


#数组的拼接
#竖直
t3=np.vstack((t1,t2))
print(t3)
#水平
t4=np.hstack((t1,t2))
print(t4)


#数组的分割
t5=np.vsplit(t1,2)
print(t5)
t6=np.hsplit(t2,2)
print(t6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[12, 13, 14],
       [18, 19, 20]]), array([[15, 16, 17],
       [21, 22, 23]])]
