In [2]:
import numpy as np
t1=np.array([[0,1,2,3,4,5]
            ,[6,7,8,9,10,11]
             ])
t2=np.arange(12,24).reshape(2,6)
print(t1)
print(t2)


#数组的拼接
t3=np.vstack((t1,t2))
print(t3)

t4=np.hstack((t1,t2))
print(t4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]
