In [1]:
import numpy as np
arr=np.arange(10)
print(arr[1])
#从索引二开始到索引7停止,间隔为2

1


In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
s = slice(2,7,2)#start   stop   step
arr[s]

array([2, 4, 6])

start:stop:step

In [7]:
arr2=arr[2:7:2]
arr2

array([2, 4, 6])

多维数组也同理