In [11]:
import numpy as np

UK_path='UK_video_data.csv'
US_path='US_video_data.csv'
t1=np.loadtxt(US_path,delimiter=',',dtype=int)
t2=np.loadtxt(UK_path,delimiter=',',dtype=int)
print(t1,len(t1))
print('*'*50)
print(t2,len(t2))


t2=np.arange(24).reshape(4,6)
print(t2)
print(t2.transpose())###  transpose()转置
print('T',
      t2.T)
print(t2)
print('swapaxes',
      t2.swapaxes(1,0))

[[152347   8921    456   1234]
 [187654   9845    521   1567]
 [212890  12356    689   1890]
 [198762  11023    712   1754]
 [234567  13567    845   2012]
 [176543  10234    598   1456]
 [201456  12056    732   1987]
 [245678  14234    912   2234]
 [165432   9567    501   1345]
 [199876  11543    745   1876]
 [223456  12890    802   2101]
 [189012  10876    623   1654]
 [211234  12234    765   1990]
 [256789  15012    987   2456]
 [178901  10123    589   1489]
 [204567  12456    778   2011]
 [236789  13901    890   2289]
 [167890   9789    534   1390]
 [194567  11345    721   1845]
 [220123  12678    832   2090]
 [155678   9210    498   1290]
 [188901  10567    576   1623]
 [215678  12901    854   2178]
 [200123  11123    701   1765]
 [238901  14012    934   2345]
 [172345  10012    567   1423]
 [207890  12789    790   2045]
 [240123  15123    999   2501]
 [163456   9432    511   1356]
 [196789  11765    756   1889]
 [225678  13234    865   2201]
 [181234  10345    612   1589]
 [213456