In [12]:
import numpy as np
#reshape
t4=np.arange(12)
print(t4)
print(t4.reshape(3,4))#变形

t5=np.arange(24).reshape(2,3,4)
print('t5',t5)
print(t5.reshape(4,6))

t5=t5.reshape(4,6)
print(t5)

t5=t5.reshape(-1)
print('reshape(-1)',t5)


t5=t5.flatten()
print('flatten()',t5)

print(t5+2)#numpy的广播机制



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
t5 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshape(-1) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
flatten() [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
