In [9]:
import numpy as np

t6=np.arange(0,6)
t7=np.array([0,1,2,3,4,5])
t5=np.arange(24).reshape(4,6)


print('t5-5',t5-5)

print(t5-t7)
t8=np.arange(4).reshape(4,1)
print(t8)
print(t5-t8)

t9=np.array([0,1,2,3,4,5,6,7,8,9])

t5-5 [[-5 -4 -3 -2 -1  0]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]
