In [13]:
import numpy as np

t1=np.arange(100).reshape(20,5)
print(t1)
x=t1.sum(axis=1)
y=t1.sum(axis=0)
print(x)
print(y)
a=t1.mean(axis=0)
print(a)
# b=t1.median(axis=0)
# print(b)
c=t1.std(t1,axis=0)
print(c)
d=t1.ptp(axis=0)
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[ 10  35  60  85 110 135 160 185 210 235 260 285 310 335 360 385 410 435
 460 485]
[ 950  970  990 1010 1030]
[47.5 48.5 49.5 50.5 51.5]


TypeError: _std() got multiple values for argument 'axis'