In [7]:
import numpy as np


#
# print(t1)
def fill_ndarray(t1):
    for i in range(t1.shape[1]):#遍历每一列
        temp_col = t1[:,i]#当前的一列

        nan_number = np.count_nonzero(temp_col!=temp_col)

        if nan_number!=0:#不为0,说明当前着一列中有nan
            temp_not_nan_col=temp_col[temp_col==temp_col]=np.nan#当前这一列不为nan的array

            temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()#选中当前为nan的位置替换成均值

    return t1
if __name__ == '__main__':
    t1=np.arange(24).reshape(4,6).astype("float")


    t1[1,2:]=np.nan
    print(t1)
    t1=fill_ndarray(t1)
    print(t1)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. nan nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


AttributeError: 'float' object has no attribute 'mean'