In [2]:
import numpy as np

def fill_ndarray(t1):
    for i in range(t1.shape[1]):  # 遍历每一列
        temp_col = t1[:, i]  # 当前的一列
        # 找出非 NaN 并计算均值
        non_nan_values = temp_col[~np.isnan(temp_col)]
        if len(non_nan_values) > 0:
            mean_value = np.mean(non_nan_values)
            # 将 NaN 值替换为均值
            t1[np.isnan(t1[:, i]), i] = mean_value
    return t1

if __name__ == '__main__':
    t1 = np.arange(24).reshape(4, 6).astype("float")
    t1[1, 2:] = np.nan
    print("\nOriginal array:")
    print(t1)
    t1 = fill_ndarray(t1)
    print("\nArray after filling NaN values:")
    print(t1)


Original array:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. nan nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]

Array after filling NaN values:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. 12. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
